name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate HMAC and trigger deploy
        run: |
          TIMESTAMP=$(date +%s)
          SECRET="cm2XPTafDzD7qugaLkCdXXDrnyM5HtqDBCPBBCginhAajyYMBeHW"

          SIGNATURE=$(echo -n "${TIMESTAMP}${SECRET}" | sha256sum | awk '{print $1}')

          curl -i -X POST "https://firebrick-eel-667446.hostingersite.com/deploy.php" \
            -d "ts=$TIMESTAMP" \
            -d "sig=$SIGNATURE"