name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        run: |
          curl "https://firebrick-eel-667446.hostingersite.com/deploy.php/?key=3grGfuZUQxw8CX0AzhAZ8w8f7B353ff2Q8hADQfbPY8mM"